### ISSUE TITLE
Create Schema dataclass

### ISSUE THREAD

**Issue by joseprsm** [joseprsm/rexify#5]
Move validations from the `HasSchemaInput` class to a `Schema` dataclass.

## Tasks
- [x] `Schema` dataclass
- [x] create dataclass for user and items
- [x] validate inputs (must have `id` field for users and items, for example)
- [x] validate event types
- [x] validate rating features
