### ISSUE TITLE
Create single preprocessing pipeline

### ISSUE THREAD

**Issue by joseprsm** [joseprsm/rexify#6]
Join user, item and event preprocessing pipelines (`FeatureExtractor`s, `EventGenerator`) in a single one.

## Tasks
- [x] Refactor `FeatureExtractor`
- [x] Pass user and item data to `EventGenerator`
  - [x] as `pandas.DataFrames`; or
  - [x] as paths (need to specify something like `load_fn=pd.read_csv`)
- [x] Should be able to access each (user, item) `IdEncoder`s
